// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MlkAdmin._3_Infrastructure.DataBase;

#nullable disable

namespace MlkAdmin.Migrations
{
    [DbContext(typeof(MlkAdminDbContext))]
    [Migration("20251117040607_ModifyStatsModel")]
    partial class ModifyStatsModel
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.10");

            modelBuilder.Entity("MlkAdmin._1_Domain.Entities.TextChannel", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelName")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Texts");
                });

            modelBuilder.Entity("MlkAdmin._1_Domain.Entities.User", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("BirthdayDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscordDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<string>("DiscordGlobalName")
                        .HasColumnType("TEXT");

                    b.Property<ulong>("GuildId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("GuildJoinedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IrlName")
                        .HasColumnType("TEXT");

                    b.Property<string>("LobbyName")
                        .HasColumnType("TEXT");

                    b.Property<string>("TgLink")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("MlkAdmin._1_Domain.Entities.UserMessagesStat", b =>
                {
                    b.Property<ulong>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BadWordsAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CommandsAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("GifsAmount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastUpdate")
                        .HasColumnType("TEXT");

                    b.Property<int>("PicturesAmount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("TotalMessageCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("UserId");

                    b.ToTable("Messages");
                });

            modelBuilder.Entity("MlkAdmin._1_Domain.Entities.UserVoiceSession", b =>
                {
                    b.Property<ulong>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalSeconds")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("VoiceStarting")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId");

                    b.ToTable("VoiceSession");
                });

            modelBuilder.Entity("MlkAdmin._1_Domain.Entities.VoiceChannel", b =>
                {
                    b.Property<ulong>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Category")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelName")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsGenerating")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsTemporary")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Voices");
                });
#pragma warning restore 612, 618
        }
    }
}
